POST /api/auth/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "example_user",
    "password": "example_password"
}

###
POST /api/auth/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###
POST /api/auth/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}